version: "3.8"

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}"

  app:
    depends_on:
      - mysqldb
    restart: on-failure
    build:
      context: .
    image: posts-service
    env_file: .env
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
    environment:
      SPRING_APPLICATION_JSON: >-
        {
          "spring.datasource.url": "jdbc:mysql://mysqldb:3306/${MYSQL_DATABASE}",
          "spring.datasource.username": "${MYSQL_ROOT_USER}",
          "spring.datasource.password": "${MYSQL_ROOT_PASSWORD}",
          "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQLDialect"
        }
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8080"
